### ISSUE TITLE
withInit() breaking change?

### ISSUE THREAD

**Issue by starmandeluxe** [TNG/sinon-helpers#88]
Previously I have been using the v1 "afterCreation" method with much success:

```
var someClassStub = sinonHelpers.getStubConstructor(SomeClass).afterCreation((instance) => {
      instance.someObject.returns({ /* return some stuff */ });
```

But after updating it to v2 like so:

```
var someClassStub = sinonHelpers.getStubConstructor(SomeClass).withInit((instance) => {
      instance.someObject.returns({ /* return some stuff */ });
```

I get an error when running my test:

> TypeError { message: instance.someObject.returns is not a function }

Why?

**Comment by lukastaegert** [comment]
Does `someObject` exist on `SomeClass`'s prototype and is it actually a function? Otherwise no default mock will be created and the best you can do is just manually add a mock via

```js
var someClassStub = sinonHelpers.getStubConstructor(SomeClass).withInit((instance) => {
      instance.someObject = sinon.stub().returns({ /* return some stuff */ });
```

But if this method exists on the prototype it should actually work. Just confirmed that locally:

```js
const SomeClassStub = sinonHelpers.getStubConstructor(class {someMethod () {}})
      .withInit((instance) => instance.someMethod.returns(3));
const instance = new SomeClassStub();
assert.equal(instance.someMethod(), 3); 
```

Might be interesting to log what `instance` actually looks like. If this is something that worked for v1 but no longer works for v2, then it would be helpful to see how `someObject` becomes part of the prototype chain.

**Comment by starmandeluxe** [comment]
Sorry, wasn't able to get a chance to investigate this until now. I figured out the issue. Indeed it does work as you say. There was a breaking change in the updated npm package I was using that required using {} in the require, which wasn't in my unit test class require call. This caused the imported object to be undefined.
